; Minimal ESP-NOW MWE targets:
; - main_node: regular ESP32 receiver
; - mini_node: ESP32-C3 sender

[platformio]
default_envs = main_node

[env]
platform = espressif32
framework = arduino
upload_speed = 115200
monitor_speed = 115200

[env:main_node]
board = esp32dev
build_src_filter =
  +<main_node.cpp>
  +<espnow_common.h>

[env:mini_node]
board = esp32-c3-devkitm-1
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
build_src_filter =
  +<mini_node.cpp>
  +<espnow_common.h>
